---
name: Renew Cert
"on":
  schedule:
    # Renew monthly: every first day of the month at 07:19.
    - cron: "19 7 1 * *"

jobs:

  renew-cert:
    name: Renew Let's Encrypt Certificate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v3.1.1
        with:
          python-version: '3.9'
      - name: Install certbot
        run: |
          python -m pip install --upgrade pip
          pip install certbot-s3front
      - name: Renew Cert
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          certbot --agree-tos
          -a certbot-s3front:auth
          --certbot-s3front:auth-s3-bucket kevin.deldycke.com
          --certbot-s3front:auth-s3-region us-east-1
          -i certbot-s3front:installer
          --certbot-s3front:installer-cf-distribution-id EUI0N3OAXXXYY
          -d kevin.deldycke.com
          --renew-by-default
          --text
          --config-dir ./letsencrypt
          --logs-dir   ./letsencrypt/logs
          --work-dir   ./letsencrypt
          --non-interactive
          --email kevin@deldycke.com
