---
name: Renew Cert
"on":
  schedule:
    # Every day at 07:19.
    - cron: "19 7 * * *"
  push:
    branches:
      - main
    paths:
      # Triggers on any workflow self-update.
      - .github/workflows/cert-renew.yaml

jobs:

  renew-cert:
    name: Renew Let's Encrypt Certificate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'
      - name: Install certbot
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Renew Cert
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          certbot --agree-tos
          -a certbot-s3front:auth
          --certbot-s3front:auth-s3-bucket kevin.deldycke.com
          --certbot-s3front:auth-s3-region us-east-1
          -i certbot-s3front:installer
          --certbot-s3front:installer-cf-distribution-id EUI0N3OAXXXYY
          -d kevin.deldycke.com
          --config-dir ./letsencrypt
          --logs-dir   ./letsencrypt/logs
          --work-dir   ./letsencrypt
          --non-interactive
          --email kevin@deldycke.com
